### ISSUE TITLE
Add sliders and image tab

### ISSUE THREAD

**Issue by infoweb-internet-solutions** [infoweb-internet-solutions/yii2-cms-pages#14]
- [x] If the `enableSliders` setting is enabled in the module, an extra tab should be shown for the selection of the slider instead of displaying it in the **data** tab
- [x] An extra setting, `enableImage` should be added, the same way that the `enableSliders` setting works, for setting a possible image that can be displayed in a fixed position on the page

**Comment by kurt0015** [comment]
done.
